// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFFTa5H5BE1Z_xzq3F0DNTM8AxL2ZmvF4',
    appId: '1:948737216499:web:9d8e64de1f9bb941478c86',
    messagingSenderId: '948737216499',
    projectId: 'e-5d676',
    authDomain: 'e-5d676.firebaseapp.com',
    storageBucket: 'e-5d676.firebasestorage.app',
    measurementId: 'G-Z37HQM74BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJdaP6kyOYRVkxbniOxgBXFnyhk2-G4M',
    appId: '1:948737216499:android:f3207c65639ff8d1478c86',
    messagingSenderId: '948737216499',
    projectId: 'e-5d676',
    storageBucket: 'e-5d676.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQS1zYz1_mzcXegwaTeIFyv3KjpBtf-w',
    appId: '1:948737216499:ios:4d58ddf0b344b892478c86',
    messagingSenderId: '948737216499',
    projectId: 'e-5d676',
    storageBucket: 'e-5d676.firebasestorage.app',
    iosBundleId: 'com.example.eAmazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQS1zYz1_mzcXegwaTeIFyv3KjpBtf-w',
    appId: '1:948737216499:ios:4d58ddf0b344b892478c86',
    messagingSenderId: '948737216499',
    projectId: 'e-5d676',
    storageBucket: 'e-5d676.firebasestorage.app',
    iosBundleId: 'com.example.eAmazon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFFTa5H5BE1Z_xzq3F0DNTM8AxL2ZmvF4',
    appId: '1:948737216499:web:f632ca1eef3d2277478c86',
    messagingSenderId: '948737216499',
    projectId: 'e-5d676',
    authDomain: 'e-5d676.firebaseapp.com',
    storageBucket: 'e-5d676.firebasestorage.app',
    measurementId: 'G-3GHWH2HMQ1',
  );
}
